# fly.toml app configuration file generated for cola on 2026-03-27T01:17:22Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cola'
primary_region = 'sin'

[build]

# fly.toml updates

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true # Change 'stop' to true
  auto_start_machines = true
  min_machines_running = 0
  protocol = "tcp"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512 # Increase this to 512 for a smoother build/run experience