# fly.toml app configuration file generated for cola on 2026-03-27T01:17:22Z

app = 'cola'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  protocol = "tcp"
  processes = ["app"]  # ✅ Link service to your app process

[processes]
  app = "NODE_ENV=production tsx server.ts"
  
[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512